version: '3'
services:
  dnsmasq:
    image: 4km3/dnsmasq
    container_name: dnsmasq_container
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - './dnsmasq.d:/etc/dnsmasq.d'
      - './resolv_conf:/etc/resolv_conf'
      - ./log:/var/log
    cap_add:
      - NET_ADMIN